name: Clear CloudFront Cache
on:
  workflow_call:
    inputs:
      base-path:
        required: true
        type: string
      distribution-id:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}
      - name: Clear CloudFront Content
        run: |
          aws lambda invoke --function-name clear-cloudfront-cache-by-github-action --cli-binary-format raw-in-base64-out --payload '{ "distribution_id": "${{ inputs.distribution-id }}", "items": ["/${{ inputs.base-path }}/*"] }' /dev/stdout
